export type GlossaryTerm = {
  id: string;
  term: string;
  category: "FBLA" | "Parliamentary" | "Business" | "Finance" | "Marketing" | "Technology" | "Leadership";
  definition: string;
  related: string[];
};

function slug(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const seed: Array<Omit<GlossaryTerm, "id">> = [
  { term: "FBLA", category: "FBLA", definition: "Future Business Leaders of America, a national career and technical student organization.", related: ["NLC", "SLC", "DLC"] },
  { term: "NLC", category: "FBLA", definition: "National Leadership Conference where top qualifiers compete nationally.", related: ["SLC", "DLC"] },
  { term: "SLC", category: "FBLA", definition: "State Leadership Conference, the state-level FBLA competition event.", related: ["NLC", "DLC"] },
  { term: "DLC", category: "FBLA", definition: "District Leadership Conference, often the first competition level.", related: ["SLC", "NLC"] },
  { term: "Competitive Event", category: "FBLA", definition: "An FBLA contest where members demonstrate business or leadership skills.", related: ["Objective Test", "Role Play", "Presentation"] },
  { term: "Officer Team", category: "FBLA", definition: "Student leaders elected to run chapter operations and initiatives.", related: ["President", "Secretary", "Treasurer"] },
  { term: "BAA", category: "FBLA", definition: "Business Achievement Awards program with milestone-level achievements.", related: ["Bronze", "Silver", "Gold"] },
  { term: "Chapter", category: "FBLA", definition: "Local school-based FBLA organization unit.", related: ["Adviser", "Officer Team"] },
  { term: "Adviser", category: "FBLA", definition: "Educator supporting chapter operations and compliance.", related: ["Chapter", "Officer Team"] },
  { term: "Who’s Who", category: "FBLA", definition: "Recognition program honoring outstanding FBLA members.", related: ["Awards", "Recognition"] },

  { term: "Main Motion", category: "Parliamentary", definition: "A proposal that introduces new business to an assembly.", related: ["Second", "Amend"] },
  { term: "Second", category: "Parliamentary", definition: "A statement indicating support to discuss a motion.", related: ["Main Motion", "Debate"] },
  { term: "Amend", category: "Parliamentary", definition: "To change wording or meaning of a motion.", related: ["Main Motion", "Friendly Amendment"] },
  { term: "Point of Order", category: "Parliamentary", definition: "Raised when a member believes rules are being violated.", related: ["Chair", "Rules"] },
  { term: "Quorum", category: "Parliamentary", definition: "Minimum number of members needed to conduct business.", related: ["Meeting", "Vote"] },
  { term: "Adjourn", category: "Parliamentary", definition: "To formally end a meeting session.", related: ["Meeting", "Agenda"] },
  { term: "Previous Question", category: "Parliamentary", definition: "Motion used to close debate and move to an immediate vote.", related: ["Debate", "Vote"] },
  { term: "Table", category: "Parliamentary", definition: "To temporarily set aside a motion.", related: ["Main Motion", "Take from the Table"] },
  { term: "Minutes", category: "Parliamentary", definition: "Official written record of meeting proceedings.", related: ["Secretary", "Agenda"] },
  { term: "Chair", category: "Parliamentary", definition: "Officer presiding over a meeting and enforcing rules.", related: ["President", "Point of Order"] },
  { term: "Debate", category: "Parliamentary", definition: "Structured discussion before voting on a motion.", related: ["Main Motion", "Vote"] },
  { term: "Majority Vote", category: "Parliamentary", definition: "More than half of votes cast.", related: ["Vote", "Two-Thirds Vote"] },
  { term: "Two-Thirds Vote", category: "Parliamentary", definition: "Higher voting threshold for certain motions.", related: ["Majority Vote", "Previous Question"] },
  { term: "Unanimous Consent", category: "Parliamentary", definition: "Decision made without formal vote if no objection is raised.", related: ["Objection", "Chair"] },
  { term: "Agenda", category: "Parliamentary", definition: "Planned order of business for a meeting.", related: ["Minutes", "Adjourn"] },
  { term: "Call to Order", category: "Parliamentary", definition: "Formal start of a meeting by the chair.", related: ["Chair", "Agenda"] },
  { term: "Friendly Amendment", category: "Parliamentary", definition: "An amendment accepted by motion maker without formal vote, depending on rules.", related: ["Amend", "Main Motion"] },
  { term: "Division of the Assembly", category: "Parliamentary", definition: "Request for a counted vote when the voice vote is unclear.", related: ["Vote", "Chair"] },
  { term: "Appeal", category: "Parliamentary", definition: "Challenge to the chair’s ruling.", related: ["Chair", "Point of Order"] },
  { term: "Standing Rules", category: "Parliamentary", definition: "Administrative rules governing chapter operations.", related: ["Bylaws", "Procedure"] },
  { term: "Bylaws", category: "Parliamentary", definition: "Core governing rules of the chapter.", related: ["Standing Rules", "Constitution"] },
  { term: "Roll Call Vote", category: "Parliamentary", definition: "Recorded vote by member name.", related: ["Vote", "Minutes"] },
  { term: "Committee Report", category: "Parliamentary", definition: "Update from a committee to the chapter.", related: ["Committee", "Agenda"] },
  { term: "Special Committee", category: "Parliamentary", definition: "Temporary committee for a specific task.", related: ["Committee", "Report"] },
  { term: "Subordinate Motion", category: "Parliamentary", definition: "Motion affecting how a main motion is handled.", related: ["Main Motion", "Amend"] },

  { term: "SWOT Analysis", category: "Business", definition: "Framework for strengths, weaknesses, opportunities, and threats.", related: ["Strategy", "Planning"] },
  { term: "Value Proposition", category: "Business", definition: "Clear statement of customer value delivered by a product/service.", related: ["Target Market", "Differentiation"] },
  { term: "Target Market", category: "Business", definition: "Specific customer group a product is designed for.", related: ["Segmentation", "Positioning"] },
  { term: "KPI", category: "Business", definition: "Key Performance Indicator used to measure success.", related: ["Metric", "Dashboard"] },
  { term: "Benchmark", category: "Business", definition: "Reference point used to compare performance.", related: ["KPI", "Best Practice"] },
  { term: "SMART Goal", category: "Business", definition: "Goal framework: Specific, Measurable, Achievable, Relevant, Time-bound.", related: ["Planning", "Execution"] },
  { term: "Stakeholder", category: "Business", definition: "Any person or group affected by a business decision.", related: ["Shareholder", "Customer"] },
  { term: "Business Model", category: "Business", definition: "How an organization creates, delivers, and captures value.", related: ["Revenue Model", "Operations"] },
  { term: "Revenue Model", category: "Business", definition: "Method by which a company earns money.", related: ["Pricing", "Sales"] },
  { term: "Cost Structure", category: "Business", definition: "Composition of fixed and variable costs in an organization.", related: ["Break-even", "Margin"] },
  { term: "Break-even Point", category: "Business", definition: "Sales level where total revenue equals total cost.", related: ["Fixed Cost", "Contribution Margin"] },
  { term: "Contribution Margin", category: "Business", definition: "Revenue minus variable costs, used to cover fixed costs.", related: ["Break-even", "Pricing"] },
  { term: "Operations", category: "Business", definition: "Processes used to produce and deliver products/services.", related: ["Supply Chain", "Quality"] },
  { term: "Supply Chain", category: "Business", definition: "Network moving products from suppliers to customers.", related: ["Logistics", "Inventory"] },
  { term: "Inventory Turnover", category: "Business", definition: "How often inventory is sold/replaced over a period.", related: ["COGS", "Demand"] },
  { term: "Customer Retention", category: "Business", definition: "Ability to keep customers over time.", related: ["Loyalty", "Churn"] },
  { term: "Churn", category: "Business", definition: "Rate at which customers stop using a product/service.", related: ["Retention", "Lifetime Value"] },
  { term: "Lifetime Value", category: "Business", definition: "Expected revenue from a customer over relationship duration.", related: ["CAC", "Retention"] },
  { term: "CAC", category: "Business", definition: "Customer Acquisition Cost: average cost to gain a new customer.", related: ["Lifetime Value", "Marketing"] },
  { term: "Differentiation", category: "Business", definition: "Strategy for standing out from competitors.", related: ["Value Proposition", "Brand"] },
  { term: "Lean Startup", category: "Business", definition: "Approach emphasizing rapid iteration and validated learning.", related: ["MVP", "Pivot"] },
  { term: "MVP", category: "Business", definition: "Minimum Viable Product with core functionality for feedback.", related: ["Lean Startup", "Iteration"] },
  { term: "Pivot", category: "Business", definition: "Strategic shift in business model or product direction.", related: ["Lean Startup", "Validation"] },
  { term: "Corporate Social Responsibility", category: "Business", definition: "Company responsibility for social/environmental impact.", related: ["Ethics", "Sustainability"] },
  { term: "Business Ethics", category: "Business", definition: "Moral principles guiding business decisions.", related: ["CSR", "Compliance"] },
  { term: "Compliance", category: "Business", definition: "Adherence to laws, policies, and regulations.", related: ["Risk", "Audit"] },
  { term: "Risk Assessment", category: "Business", definition: "Identifying and evaluating potential threats.", related: ["Mitigation", "Compliance"] },
  { term: "Mitigation", category: "Business", definition: "Actions taken to reduce risk likelihood or impact.", related: ["Risk Assessment", "Controls"] },
  { term: "Change Management", category: "Business", definition: "Structured approach to organizational change.", related: ["Leadership", "Communication"] },
  { term: "Organizational Culture", category: "Business", definition: "Shared values and behaviors within an organization.", related: ["Leadership", "Engagement"] },
  { term: "Delegation", category: "Leadership", definition: "Assigning responsibility and authority to others.", related: ["Accountability", "Management"] },
  { term: "Accountability", category: "Leadership", definition: "Being responsible for outcomes and decisions.", related: ["Ownership", "Execution"] },

  { term: "Assets", category: "Finance", definition: "Resources with economic value owned by an entity.", related: ["Liabilities", "Equity"] },
  { term: "Liabilities", category: "Finance", definition: "Financial obligations owed to others.", related: ["Assets", "Equity"] },
  { term: "Equity", category: "Finance", definition: "Residual interest after liabilities are subtracted from assets.", related: ["Assets", "Liabilities"] },
  { term: "Balance Sheet", category: "Finance", definition: "Statement showing assets, liabilities, and equity at a point in time.", related: ["Income Statement", "Cash Flow"] },
  { term: "Income Statement", category: "Finance", definition: "Statement of revenues and expenses over a period.", related: ["Profit", "Margin"] },
  { term: "Cash Flow Statement", category: "Finance", definition: "Tracks cash from operations, investing, and financing activities.", related: ["Liquidity", "Operations"] },
  { term: "Gross Profit", category: "Finance", definition: "Revenue minus cost of goods sold.", related: ["Gross Margin", "COGS"] },
  { term: "Net Income", category: "Finance", definition: "Profit after all expenses and taxes.", related: ["Income Statement", "EPS"] },
  { term: "COGS", category: "Finance", definition: "Cost of Goods Sold, direct costs of producing sold goods.", related: ["Gross Profit", "Inventory"] },
  { term: "Gross Margin", category: "Finance", definition: "Gross profit as a percentage of revenue.", related: ["Gross Profit", "Net Margin"] },
  { term: "Operating Margin", category: "Finance", definition: "Operating income divided by revenue.", related: ["EBIT", "Efficiency"] },
  { term: "Net Margin", category: "Finance", definition: "Net income divided by revenue.", related: ["Net Income", "Profitability"] },
  { term: "Current Ratio", category: "Finance", definition: "Current assets divided by current liabilities.", related: ["Liquidity", "Working Capital"] },
  { term: "Quick Ratio", category: "Finance", definition: "Liquidity measure excluding inventory from current assets.", related: ["Current Ratio", "Liquidity"] },
  { term: "Working Capital", category: "Finance", definition: "Current assets minus current liabilities.", related: ["Liquidity", "Operations"] },
  { term: "Depreciation", category: "Finance", definition: "Allocation of asset cost over useful life.", related: ["Amortization", "Expense"] },
  { term: "Amortization", category: "Finance", definition: "Expense recognition of intangible assets over time.", related: ["Depreciation", "Intangible"] },
  { term: "Interest Expense", category: "Finance", definition: "Cost of borrowing funds.", related: ["Debt", "Coverage Ratio"] },
  { term: "Debt-to-Equity", category: "Finance", definition: "Leverage ratio comparing total debt to shareholder equity.", related: ["Leverage", "Risk"] },
  { term: "Return on Equity", category: "Finance", definition: "Net income divided by shareholder equity.", related: ["ROA", "Profitability"] },
  { term: "Return on Assets", category: "Finance", definition: "Net income divided by total assets.", related: ["ROE", "Efficiency"] },
  { term: "EPS", category: "Finance", definition: "Earnings Per Share, profit allocated to each share.", related: ["P/E Ratio", "Net Income"] },
  { term: "P/E Ratio", category: "Finance", definition: "Price-to-Earnings ratio used to value stocks.", related: ["EPS", "Valuation"] },
  { term: "Dividend", category: "Finance", definition: "Distribution of earnings to shareholders.", related: ["Retained Earnings", "Yield"] },
  { term: "Yield", category: "Finance", definition: "Income return on an investment.", related: ["Dividend", "Interest"] },
  { term: "Present Value", category: "Finance", definition: "Current value of future cash flows discounted at a rate.", related: ["Future Value", "Discount Rate"] },
  { term: "Future Value", category: "Finance", definition: "Value of an investment at a future date.", related: ["Present Value", "Compounding"] },
  { term: "Compound Interest", category: "Finance", definition: "Interest calculated on principal plus accumulated interest.", related: ["Future Value", "APR"] },
  { term: "APR", category: "Finance", definition: "Annual Percentage Rate representing yearly borrowing cost.", related: ["Interest", "Loan"] },
  { term: "Liquidity", category: "Finance", definition: "How easily assets can be converted to cash.", related: ["Current Ratio", "Cash Flow"] },

  { term: "Market Segmentation", category: "Marketing", definition: "Dividing a market into distinct consumer groups.", related: ["Target Market", "Positioning"] },
  { term: "Positioning", category: "Marketing", definition: "How a brand is perceived in the minds of consumers.", related: ["Brand", "Differentiation"] },
  { term: "Brand Equity", category: "Marketing", definition: "Value derived from consumer perception of a brand.", related: ["Brand Awareness", "Loyalty"] },
  { term: "Brand Awareness", category: "Marketing", definition: "How well consumers recognize a brand.", related: ["Reach", "Impressions"] },
  { term: "Reach", category: "Marketing", definition: "Number of unique people exposed to a message.", related: ["Impressions", "Frequency"] },
  { term: "Impressions", category: "Marketing", definition: "Total number of times content is displayed.", related: ["Reach", "CPM"] },
  { term: "CTR", category: "Marketing", definition: "Click-Through Rate, percentage of impressions that generate clicks.", related: ["Conversion Rate", "CPC"] },
  { term: "Conversion Rate", category: "Marketing", definition: "Percentage of users completing desired action.", related: ["CTR", "Funnel"] },
  { term: "Funnel", category: "Marketing", definition: "Stages from awareness to conversion.", related: ["Conversion Rate", "Retention"] },
  { term: "CPM", category: "Marketing", definition: "Cost per thousand impressions.", related: ["CPC", "Ad Spend"] },
  { term: "CPC", category: "Marketing", definition: "Cost per click in digital advertising.", related: ["CTR", "CPM"] },
  { term: "A/B Testing", category: "Marketing", definition: "Comparing two versions to determine better performance.", related: ["Optimization", "Conversion"] },
  { term: "Content Strategy", category: "Marketing", definition: "Plan for creating and distributing content aligned to goals.", related: ["Engagement", "Brand"] },
  { term: "Engagement Rate", category: "Marketing", definition: "Interaction level relative to audience size.", related: ["Reach", "Content Strategy"] },
  { term: "Call to Action", category: "Marketing", definition: "Prompt encouraging users to take a specific step.", related: ["Conversion", "Funnel"] },
  { term: "Customer Persona", category: "Marketing", definition: "Fictional profile representing target customer.", related: ["Segmentation", "Target Market"] },
  { term: "Influencer Marketing", category: "Marketing", definition: "Using influential creators to promote products/services.", related: ["Reach", "Engagement"] },
  { term: "Owned Media", category: "Marketing", definition: "Channels controlled by brand like website/email list.", related: ["Earned Media", "Paid Media"] },
  { term: "Earned Media", category: "Marketing", definition: "Publicity gained organically through others.", related: ["PR", "Social Proof"] },
  { term: "Paid Media", category: "Marketing", definition: "Media exposure bought through ads/sponsorships.", related: ["CPM", "CPC"] },
  { term: "Social Proof", category: "Marketing", definition: "Influence created by customer reviews and endorsements.", related: ["Trust", "Brand"] },
  { term: "Retention Campaign", category: "Marketing", definition: "Campaign focused on keeping existing customers.", related: ["Churn", "Loyalty"] },
  { term: "Loyalty Program", category: "Marketing", definition: "Incentive program rewarding repeat customers.", related: ["Retention", "Lifetime Value"] },
  { term: "Promo Mix", category: "Marketing", definition: "Combination of advertising, PR, sales promotion, and personal selling.", related: ["Integrated Marketing"] },

  { term: "Algorithm", category: "Technology", definition: "A set of steps for solving a computational problem.", related: ["Complexity", "Data Structure"] },
  { term: "Data Structure", category: "Technology", definition: "Method of organizing data for efficient access and modification.", related: ["Algorithm", "Array"] },
  { term: "Array", category: "Technology", definition: "Ordered collection of elements indexed by position.", related: ["List", "Data Structure"] },
  { term: "Hash Map", category: "Technology", definition: "Key-value structure optimized for quick lookups.", related: ["Dictionary", "Data Structure"] },
  { term: "Stack", category: "Technology", definition: "LIFO data structure where last item added is first removed.", related: ["Queue", "Data Structure"] },
  { term: "Queue", category: "Technology", definition: "FIFO data structure where first item added is first removed.", related: ["Stack", "Data Structure"] },
  { term: "Big O", category: "Technology", definition: "Notation describing algorithm growth relative to input size.", related: ["Complexity", "Optimization"] },
  { term: "API", category: "Technology", definition: "Application Programming Interface for software communication.", related: ["Endpoint", "HTTP"] },
  { term: "Endpoint", category: "Technology", definition: "Specific URL path exposed by an API.", related: ["API", "HTTP"] },
  { term: "HTTP", category: "Technology", definition: "Protocol for data transfer on the web.", related: ["HTTPS", "Request"] },
  { term: "HTTPS", category: "Technology", definition: "Secure HTTP with encrypted communication.", related: ["SSL", "TLS"] },
  { term: "Database", category: "Technology", definition: "Structured system for storing and retrieving data.", related: ["SQL", "NoSQL"] },
  { term: "SQL", category: "Technology", definition: "Structured Query Language for relational databases.", related: ["Database", "Query"] },
  { term: "NoSQL", category: "Technology", definition: "Non-relational database model for flexible schemas.", related: ["Firestore", "Document Store"] },
  { term: "Firestore", category: "Technology", definition: "Google Firebase NoSQL document database.", related: ["Firebase", "Collections"] },
  { term: "Authentication", category: "Technology", definition: "Process of verifying user identity.", related: ["Authorization", "Token"] },
  { term: "Authorization", category: "Technology", definition: "Granting access rights after authentication.", related: ["Permissions", "Role"] },
  { term: "Token", category: "Technology", definition: "Credential used to verify requests and identity.", related: ["JWT", "Auth"] },
  { term: "Cloud Function", category: "Technology", definition: "Serverless function triggered by events or HTTP requests.", related: ["Backend", "Firebase"] },
  { term: "Version Control", category: "Technology", definition: "System to track code changes over time.", related: ["Git", "Branch"] },
  { term: "Git", category: "Technology", definition: "Distributed version control tool.", related: ["Commit", "Branch", "Merge"] },
  { term: "Branch", category: "Technology", definition: "Independent line of development in version control.", related: ["Merge", "Pull Request"] },
  { term: "Merge", category: "Technology", definition: "Combining code changes from multiple branches.", related: ["Conflict", "Branch"] },
  { term: "Unit Test", category: "Technology", definition: "Automated test for smallest functional code units.", related: ["Integration Test", "CI"] },
  { term: "Integration Test", category: "Technology", definition: "Test validating interactions between system parts.", related: ["Unit Test", "E2E Test"] },
  { term: "E2E Test", category: "Technology", definition: "End-to-end test covering user-level workflows.", related: ["Integration Test", "QA"] },
  { term: "UI/UX", category: "Technology", definition: "User Interface and User Experience design principles.", related: ["Accessibility", "Usability"] },
  { term: "Accessibility", category: "Technology", definition: "Designing interfaces usable by people with diverse abilities.", related: ["Contrast", "Screen Reader"] },
  { term: "Encryption", category: "Technology", definition: "Securing data by converting it into coded form.", related: ["Security", "TLS"] },
  { term: "Cybersecurity", category: "Technology", definition: "Practice of protecting systems, networks, and data.", related: ["Threat", "Mitigation"] },

  { term: "Active Listening", category: "Leadership", definition: "Listening to understand before responding.", related: ["Communication", "Empathy"] },
  { term: "Conflict Resolution", category: "Leadership", definition: "Methods used to resolve disagreements constructively.", related: ["Negotiation", "Communication"] },
  { term: "Facilitation", category: "Leadership", definition: "Guiding a group process toward productive outcomes.", related: ["Meeting", "Agenda"] },
  { term: "Time Blocking", category: "Leadership", definition: "Scheduling focused time blocks for key tasks.", related: ["Productivity", "Planning"] },
  { term: "Prioritization", category: "Leadership", definition: "Ranking tasks by urgency and impact.", related: ["Execution", "Time Management"] },
  { term: "Project Charter", category: "Leadership", definition: "Document defining project scope, objectives, and stakeholders.", related: ["Scope", "Project Management"] },
  { term: "Scope Creep", category: "Leadership", definition: "Uncontrolled expansion of project scope.", related: ["Project Charter", "Change Control"] },
  { term: "Milestone", category: "Leadership", definition: "Significant checkpoint in project timeline.", related: ["Timeline", "Deliverable"] },
  { term: "Deliverable", category: "Leadership", definition: "Tangible output produced by a project.", related: ["Milestone", "Scope"] },
  { term: "Retrospective", category: "Leadership", definition: "Review process to identify what worked and what to improve.", related: ["Continuous Improvement", "Team"] },
  { term: "Feedback Loop", category: "Leadership", definition: "Cycle of receiving and applying feedback for improvement.", related: ["Iteration", "Coaching"] },
  { term: "Mentorship", category: "Leadership", definition: "Guidance relationship focused on development and growth.", related: ["Coaching", "Networking"] },
  { term: "Networking", category: "Leadership", definition: "Building professional relationships that create opportunities.", related: ["Mentorship", "Communication"] },
  { term: "Executive Summary", category: "Leadership", definition: "Concise overview of key findings and recommendations.", related: ["Report", "Presentation"] },
  { term: "Elevator Pitch", category: "Leadership", definition: "Short persuasive summary of idea or value proposition.", related: ["Presentation", "Communication"] },
  { term: "Storytelling", category: "Leadership", definition: "Using narrative structure to communicate and persuade.", related: ["Presentation", "Engagement"] },
  { term: "Body Language", category: "Leadership", definition: "Nonverbal communication through posture, gestures, and expression.", related: ["Presentation", "Confidence"] },
  { term: "Vocal Variety", category: "Leadership", definition: "Use of pace, tone, and emphasis for engaging speech.", related: ["Public Speaking", "Delivery"] },
  { term: "Q&A Handling", category: "Leadership", definition: "Responding clearly and confidently to judge questions.", related: ["Preparation", "Composure"] },
  { term: "Professionalism", category: "Leadership", definition: "Demonstrating reliability, ethics, and respect in conduct.", related: ["Etiquette", "Communication"] },
];

export const FBLA_GLOSSARY_TERMS: GlossaryTerm[] = seed.map((entry) => ({
  ...entry,
  id: slug(entry.term),
}));

